### ISSUE TITLE
To Do 40?

### ISSUE THREAD

**Issue by Docmine17** [flathub/org.gnome.Todo#14]

**Comment by hfiguiere** [comment]
See #12

**Comment by GeorgesStavracas** [comment]
Merged

**Comment by lightonflux** [comment]
There is some issue with the flatpak i think. 
Metadata indicates version 40, but checking within the application returns 3.28:

(rpm is not installed only flatpak)
![Bildschirmfoto von 2021-06-16 11-30-35](https://user-images.githubusercontent.com/1377943/122195176-6764af00-ce96-11eb-9b7c-1423ff17d941.png)
